# Form implementation generated from reading ui file 'C:\Projects\tasks_manager\
# tasks_manager_greenatom\general_code\tasker.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from db import DataBase
import sqlite3
import sys

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Tasker(object):
    def setupUi(self, Tasker):
        """Файл создан с помощью QT Designer и вручную дописаны собственные
        функции.
        """
        Tasker.setObjectName("Tasker")
        Tasker.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=Tasker)
        self.centralwidget.setObjectName("centralwidget")
        self.fullname = QtWidgets.QLabel(parent=self.centralwidget)
        self.fullname.setGeometry(QtCore.QRect(50, 50, 111, 16))
        self.fullname.setObjectName("fullname")
        self.fullname_in = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fullname_in.setGeometry(QtCore.QRect(160, 50, 113, 20))
        self.fullname_in.setObjectName("fullname_in")
        self.name_in = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_in.setGeometry(QtCore.QRect(160, 90, 113, 20))
        self.name_in.setObjectName("name_in")
        self.name = QtWidgets.QLabel(parent=self.centralwidget)
        self.name.setGeometry(QtCore.QRect(50, 90, 111, 16))
        self.name.setObjectName("name")
        self.descript_in = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.descript_in.setGeometry(QtCore.QRect(160, 130, 113, 20))
        self.descript_in.setObjectName("descript_in")
        self.descript = QtWidgets.QLabel(parent=self.centralwidget)
        self.descript.setGeometry(QtCore.QRect(50, 130, 111, 16))
        self.descript.setObjectName("descript")
        self.priority_in = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.priority_in.setGeometry(QtCore.QRect(160, 170, 113, 20))
        self.priority_in.setObjectName("priority_in")
        self.priority = QtWidgets.QLabel(parent=self.centralwidget)
        self.priority.setGeometry(QtCore.QRect(50, 170, 111, 16))
        self.priority.setObjectName("priority")
        self.deadline_in = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.deadline_in.setGeometry(QtCore.QRect(160, 210, 113, 20))
        self.deadline_in.setObjectName("deadline_in")
        self.deadline = QtWidgets.QLabel(parent=self.centralwidget)
        self.deadline.setGeometry(QtCore.QRect(50, 210, 111, 16))
        self.deadline.setObjectName("deadline")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(150, 50, 20, 181))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.add_task = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_task.setGeometry(QtCore.QRect(280, 50, 141, 181))
        self.add_task.setStyleSheet(
            "background-color: rgb(0, 255, 0);\n"
            "background-color: rgb(255, 255, 127);\n"
            'font: 75 16pt "Arial";'
        )
        self.add_task.setObjectName("add_task")
        self.get_all = QtWidgets.QPushButton(parent=self.centralwidget)
        self.get_all.setGeometry(QtCore.QRect(20, 270, 161, 101))
        self.get_all.setObjectName("get_all")
        self.get_all_view = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.get_all_view.setGeometry(QtCore.QRect(20, 381, 761, 201))
        self.get_all_view.setObjectName("get_all_view")
        self.delete_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(510, 40, 251, 161))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.delete_2.setFont(font)
        self.delete_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.delete_2.setObjectName("delete_2")
        self.sort_fullname = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sort_fullname.setGeometry(QtCore.QRect(180, 270, 71, 101))
        self.sort_fullname.setObjectName("sort_fullname")
        self.sort_name = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sort_name.setGeometry(QtCore.QRect(250, 270, 71, 101))
        self.sort_name.setObjectName("sort_name")
        self.sort_deadline = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sort_deadline.setGeometry(QtCore.QRect(320, 270, 71, 101))
        self.sort_deadline.setObjectName("sort_deadline")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 239, 211, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "background-color: rgb(0, 255, 0);\n"
            'font: 8pt "Arial";\n'
            'font: 16pt "MS Shell Dlg 2";\n'
            'font: 75 8pt "MS Shell Dlg 2";\n'
            'font: 75 16pt "MS Shell Dlg 2";\n'
            ""
        )
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 240, 211, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(
            "background-color: rgb(0, 255, 0);\n"
            'font: 8pt "Arial";\n'
            'font: 16pt "MS Shell Dlg 2";\n'
            'font: 75 8pt "MS Shell Dlg 2";\n'
            'font: 75 16pt "MS Shell Dlg 2";\n'
            ""
        )
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.search_name = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_name.setGeometry(QtCore.QRect(480, 270, 71, 51))
        self.search_name.setObjectName("search_name")
        self.search_deadline = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_deadline.setGeometry(QtCore.QRect(550, 270, 71, 51))
        self.search_deadline.setObjectName("search_deadline")
        self.search_fullname = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_fullname.setGeometry(QtCore.QRect(410, 270, 71, 51))
        self.search_fullname.setObjectName("search_fullname")
        self.delete_id = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_id.setGeometry(QtCore.QRect(630, 270, 151, 51))
        self.delete_id.setStyleSheet(
            "background-color: rgb(255, 0, 255);\n" 'font: 75 16pt "Arial";'
        )
        self.delete_id.setObjectName("delete_id")
        self.delete_id_in = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.delete_id_in.setGeometry(QtCore.QRect(650, 330, 113, 41))
        self.delete_id_in.setStyleSheet(
            "background-color: rgb(255, 0, 255);\n" 'font: 75 16pt "Arial";'
        )
        self.delete_id_in.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.delete_id_in.setObjectName("delete_id_in")
        self.search_fullname_in = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_fullname_in.setGeometry(QtCore.QRect(410, 320, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.search_fullname_in.setFont(font)
        self.search_fullname_in.setStyleSheet("")
        self.search_fullname_in.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignCenter)
        self.search_fullname_in.setObjectName("search_fullname_in")
        self.search_name_in = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_name_in.setGeometry(QtCore.QRect(480, 320, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.search_name_in.setFont(font)
        self.search_name_in.setStyleSheet("")
        self.search_name_in.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.search_name_in.setObjectName("search_name_in")
        self.search_deadline_in = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_deadline_in.setGeometry(QtCore.QRect(550, 320, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.search_deadline_in.setFont(font)
        self.search_deadline_in.setStyleSheet("")
        self.search_deadline_in.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignCenter)
        self.search_deadline_in.setObjectName("search_deadline_in")
        Tasker.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tasker)
        QtCore.QMetaObject.connectSlotsByName(Tasker)

        self.add_functions()
        self.d_b = DataBase()

    def retranslateUi(self, Tasker):
        _translate = QtCore.QCoreApplication.translate
        Tasker.setWindowTitle(_translate(
            "Tasker", "MainWindow"))
        self.fullname.setText(_translate(
            "Tasker", "ФИО пользователя"))
        self.name.setText(_translate(
            "Tasker", "Название задачи"))
        self.descript.setText(_translate(
            "Tasker", "Описание"))
        self.priority.setText(_translate(
            "Tasker", "Приоритетность"))
        self.deadline.setText(_translate(
            "Tasker", "Срок"))
        self.add_task.setText(_translate(
            "Tasker", "Запись в БД"))
        self.get_all.setText(_translate(
            "Tasker", "Выгрузить из БД"))
        self.delete_2.setText(_translate(
            "Tasker", "УДАЛИТЬ БД"))
        self.sort_fullname.setText(_translate(
            "Tasker", "По ФИО"))
        self.sort_name.setText(_translate(
            "Tasker", "По \n" "названию\n" "задачи"))
        self.sort_deadline.setText(_translate(
            "Tasker", "По\n" " DEADLINE"))
        self.label.setText(_translate(
            "Tasker", "Сортировка"))
        self.label_2.setText(_translate("Tasker", "Поиск"))
        self.search_name.setText(_translate(
            "Tasker", "По \n" "названию\n" "задачи"))
        self.search_deadline.setText(_translate(
            "Tasker", "По\n" " DEADLINE"))
        self.search_fullname.setText(_translate(
            "Tasker", "По ФИО"))
        self.delete_id.setText(_translate(
            "Tasker", "Удалить по ID"))
        self.delete_id_in.setText(_translate("Tasker", ""))
        self.search_fullname_in.setText(_translate(
            "Tasker", ""))
        self.search_name_in.setText(_translate("Tasker", ""))
        self.search_deadline_in.setText(_translate(
            "Tasker", ""))

    def add_functions(self):
        """Функция обрабатывает взаимодействие с интерфейсом."""
        self.add_task.clicked.connect(
            lambda: self.write_tasks(
                self.fullname_in.text(),
                self.name_in.text(),
                self.descript_in.text(),
                self.priority_in.text(),
                self.deadline_in.text(),
            )
        )
        self.get_all.clicked.connect(self.get_all_tasks)

        self.delete_2.clicked.connect(self.delete2)

        self.delete_id.clicked.connect(
            lambda: self.delete_id_b(self.delete_id_in.text())
        )

        self.sort_fullname.clicked.connect(self.sort_fullname_b)
        self.sort_name.clicked.connect(self.sort_name_b)
        self.sort_deadline.clicked.connect(self.sort_deadline_b)

        self.search_fullname.clicked.connect(
            lambda: self.search_fullname_b(self.search_fullname_in.text())
        )
        self.search_name.clicked.connect(
            lambda: self.search_name_b(self.search_name_in.text())
        )
        self.search_deadline.clicked.connect(
            lambda: self.search_deadline_b(self.search_deadline_in.text())
        )

    def write_tasks(self, fn, n, d, p, dl):
        """Функция записывает новую задачу в БД.

        Args:
            fn: ФИО пользователя.
            n: Название задачи.
            d: Описание задачи.
            p: Приоритет задачи.
            dl: Срок выполнения задачи.
        """
        self.d_b.add_task(fn, n, d, p, dl)
        self.fullname_in.setText("")
        self.name_in.setText("")
        self.descript_in.setText("")
        self.priority_in.setText("")
        self.deadline_in.setText("")

    def delete_id_b(self, i_d):
        """Удаляет задачу по ID.

        Args:
            i_d: ID задачи.
        """
        self.d_b.delete(i_d)
        self.delete_id_in.setText("")

    def get_all_tasks(self):
        """Выводит список всех задач в БД.
        """
        temp = ""
        for i in self.d_b.get_all():
            temp += str(i) + "\n"
        self.get_all_view.setText(str(temp))

    def search_fullname_b(self, fio):
        """Поиск задачи по ФИО зарегистрировавшего.

        Args:
            fio: ФИО зарегистрировавшего.
        """
        self.get_all_view.setText("")
        self.get_all_view.setText(str(*self.d_b.search_fullname(fio)))
        self.search_fullname_in.setText("")

    def search_name_b(self, name):
        """Поиск по имени задачи.

        Args:
            name: Название задачи.
        """
        self.get_all_view.setText("")
        self.get_all_view.setText(str(*self.d_b.search_name(name)))
        self.search_name_in.setText("")

    def search_deadline_b(self, deadline):
        """Поиск по сроку сдачи задачи.

        Args:
            deadline: Срок сдачи.
        """
        self.get_all_view.setText("")
        self.get_all_view.setText(str(*self.d_b.search_deadline(deadline)))
        self.search_deadline_in.setText("")

    def sort_fullname_b(self):
        """Сортировка по ФИО.
        """
        self.get_all_view.setText("")
        temp = ""
        for i in self.d_b.sort_fullname():
            temp += str(i) + "\n"
        self.get_all_view.setText(str(temp))

    def sort_name_b(self):
        """Сортировка по названию задачи.
        """
        self.get_all_view.setText("")
        temp_n = ""
        for i in self.d_b.sort_name():
            temp_n += str(i) + "\n"
        self.get_all_view.setText(str(temp_n))

    def sort_deadline_b(self):
        """Сортировка по сроку сдачи задачи.
        """
        self.get_all_view.setText("")
        temp = ""
        for i in self.d_b.sort_deadline():
            temp += str(i) + "\n"
        self.get_all_view.setText(str(temp))

    def delete2(self):
        """УДАЛЯЕТ ВСЮ БД.
        """
        self.d_b.delete_all()
        self.get_all_view.setText("")


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    my_app = QtWidgets.QMainWindow()
    ui = Ui_Tasker()
    ui.setupUi(my_app)
    my_app.show()
    sys.exit(app.exec())
